name: Vulnerability Check

on: [push]

jobs:
  govulncheck_job:
    name: Go Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.23.5
          go-package: ./...
