name: Vulnerability Check

on: [push]

env:
  GO_VERSION: stable

jobs:
  govulncheck_job:
    name: Go Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: ${{ env.GO_VERSION }}
          go-package: ./...
